name: Publish Docker Image

on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image for ARM64
        run: |
          docker buildx build --platform linux/arm64 --tag ghcr.io/tiiuae/my-new-container:latest --push .

      - name: Run the Docker image
        run: |
          docker run --platform linux/arm64 ghcr.io/tiiuae/my-new-container:latest
